const hospitalSpecialties = [
    { specialty: "Anesthesiology" },
    { specialty: "Cardiology" },
    { specialty: "Dermatology" },
    { specialty: "Emergency Medicine" },
    { specialty: "Endocrinology" },
    { specialty: "Family Medicine" },
    { specialty: "Gastroenterology" },
    { specialty: "General Surgery" },
    { specialty: "Hematology" },
    { specialty: "Infectious Disease" },
    { specialty: "Internal Medicine" },
    { specialty: "Neurology" },
    { specialty: "Obstetrics and Gynecology (OB/GYN)" },
    { specialty: "Ophthalmology" },
    { specialty: "Orthopedic Surgery" },
    { specialty: "Otolaryngology (ENT)" },
    { specialty: "Pediatrics" },
    { specialty: "Psychiatry" },
    { specialty: "Pulmonology" },
    { specialty: "Radiology" },
    { specialty: "Rheumatology" },
    { specialty: "Urology" },
    { specialty: "Neurosurgery" },
    { specialty: "Plastic Surgery" },
    { specialty: "Allergy and Immunology" },
    { specialty: "Nephrology" },
    { specialty: "Geriatrics" },
    { specialty: "Pain Medicine" },
    { specialty: "Sports Medicine" },
    { specialty: "Gynecologic Oncology" },
    { specialty: "Cardiothoracic Surgery" },
    { specialty: "Interventional Radiology" },
    { specialty: "Nuclear Medicine" },
    { specialty: "Sleep Medicine" }
];

export default hospitalSpecialties;
